### ISSUE TITLE
Add "Learning JavaScript Design Patterns" by Addy Osmani

### ISSUE THREAD

**Issue by marcusstenbeck** [revolunet/JSbooks#53]
I couldn't find "Learning JavaScript Design Patterns" by Addy Osmani in the list. Please add!

I'll PR this later if you don't beat me to the chase. :)

http://addyosmani.com/resources/essentialjsdesignpatterns/book/

**Comment by revolunet** [comment]
thanks, but i think its already here : https://github.com/revolunet/JSbooks/blob/master/issues.json#L102

**Comment by marcusstenbeck** [comment]
@revolunet Ah! Sorry, my mistake. I thought I had gone through the whole thing. Cheers, then! :)

**Comment by revolunet** [comment]
Cheers :)
