### ISSUE TITLE
The provided link does not work for me

### ISSUE THREAD

**Issue by dreamtocode** [revolunet/JSbooks#70]
First thanks for taking time to create this directory of best free JavaScript resources.
I tried to check out Andy Sylvester's book called "Building Browser Apps with Google Chrome" but provided link does not work: http://www.buildbrowserapps.com/chromeappbook/index.html

**Comment by revolunet** [comment]
Thanks for reporting, the domain has been stolen....
The book is from 2012 sot not sure its still revelant. You can ask the author https://twitter.com/AndySylvester99

**Comment by dreamtocode** [comment]
Oh if that book is from 2012 than it is't interesting for me anymore. To be honest I think you should remove that one wbu?

**Comment by revolunet** [comment]
removed, thank you

**Comment by dreamtocode** [comment]
You are Welcome!
