### ISSUE TITLE
Logo for JSbooks

### ISSUE THREAD

**Issue by mirzazulfan** [revolunet/JSbooks#90]
Hi
I wanted to contribute to JSbooks and I designed a logo for JSbooks. If you like it, you can use it. I'll send you files, is there anything you want ?
![js books](https://user-images.githubusercontent.com/36124339/39167841-6aa66d76-47bb-11e8-9997-fee57bdff74d.png)
Best Regard.

**Comment by UncleBill** [comment]
Should be multiple books, or a stack of books

**Comment by mirzazulfan** [comment]
hi, wht about this ? 
![versi 3](https://user-images.githubusercontent.com/36124339/39345406-788b2a72-4a12-11e8-9ab2-629cd5c45e51.png)

**Comment by revolunet** [comment]
Hi thanks a lot !
I like the one with yellow background

**Comment by mirzazulfan** [comment]
@revolunet , I'am glad you like it. can you add in readme file? that's enough for me, or I sent you pr. Thank you.
like this :
![update readme file](https://user-images.githubusercontent.com/36124339/39370103-3cb1fc82-4a68-11e8-858a-f4076905a8fe.png)

you can download editables files (SVG, CDR, PNG, PDF) here : 
https://drive.google.com/drive/folders/1EjcnlXDWSC1U3w-y_L7q9S3AXGStWKIw

**Comment by mirzazulfan** [comment]
Hello @revolunet i've created a PR #91 Please check.
